version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5444:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  node:
    build: .
    depends_on:
      - postgres
    ports:
      - '${API_PORT}:${API_PORT}'
    env_file:
      - .env

volumes:
  postgres:
